language: emacs
sudo: false

env:
  - EVM_EMACS=emacs-25.3-travis
  - EVM_EMACS=emacs-26-pretest-travis

matrix:
  fast_finish: true

before_install:
  - curl -fsSkL https://gist.github.com/rejeep/ebcd57c3af83b049833b/raw > travis.sh && source ./travis.sh
  - evm install $EVM_EMACS --use --skip
  # Fix cask (See https://github.com/cask/cask/issues/399#issuecomment-331640427)
  - perl -ibak -lape 's{#!/usr/bin/env python}{#!/usr/bin/python}' "$(which cask)"
  - cask

install:
  - cask install

script:
  - emacs --version
  - make check
